### ISSUE TITLE
sign-in and Sign-up pages need to be fixed.

### ISSUE THREAD

**Issue by Sathya-reddy1658** [arghadipmanna101/Flipkart_Clone#27]
both login and signup pages look little odd and not properly placed on the screen , i would like to work on the issue and make it look clean and professional which enhances user experience

**Comment by arghadipmanna101** [comment]
sure. Go ahead @Sathya-reddy1658  👍

**Comment by Kochurii** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by PoojaGadagi08** [comment]
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by arghadipmanna101** [comment]
> Hello @arghadipmanna101 sir I would like to work on this issue as a contributor to the GSSOC. please assign this to me! I have relevant skills that definitely help to enhance the website.

which update you want to do?

**Comment by RiyaaBhatt** [comment]
Hello there,

As a contributor for GSSOC'24, I'm eager to tackle this issue and enhance the UI. With my background in Web Design, I can assure you that I'll create an attractive and visually appealing UI with proper formatting, fonts, and overall page design.

I kindly request you to assign this issue to me so that I can get started and contribute my skills to make the UI more appealing and user-friendly.

Thank you for considering my request!

Best regards.
