### ISSUE TITLE
Product category

### ISSUE THREAD

**Issue by pankaj-bind** [arghadipmanna101/Flipkart_Clone#69]
Assign me this task under GSSoC24, I will implement a section having product categories.

**Comment by Aditi-Gopinath** [comment]
Hello @arghadipmanna101 ! 

I hope this message finds you well. I'm excited to express my interest in contributing to the GSSoC'24 project and would like to request assignment of the issue titled "Product Category"

Having reviewed the issue description, I'm confident in my ability to make a meaningful contribution towards resolving it. Could you please confirm if this issue is available for assignment?

I'm looking forward to the opportunity to contribute to the project...

**Comment by arghadipmanna101** [comment]
Ok go ahead guys @pankaj-bind @Aditi-Gopinath

**Comment by creativeadi** [comment]
Kindly assign me this task under GSSoc24
