### ISSUE TITLE
Feat: Positioning the page up button

### ISSUE THREAD

**Issue by dharshini2022** [arghadipmanna101/Flipkart_Clone#692]
### Describe the feature

Move the page up button to the bottom corner

### Add ScreenShots

![Screenshot 2024-05-19 225656](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123349807/6554848f-7411-4107-8922-e5d4791153b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Codeoholic20** [comment]
### Existing Feature Problem
The current position of page up button/arrow is disrupting the view of user. So its better to position it at suitable point so that it doesn't come over the content and user don't have to do unnecessary movements over the page for reading.
### Screenshot
![Screenshot 2024-05-20 114835](https://github.com/arghadipmanna101/Flipkart_Clone/assets/163699974/e147403e-75bc-4ac6-b17e-32af126a1f84)
### My Record

1. I agree to follow the project's code of conduct
2. I am a GSSOC'24 contributor
3. I want to work on this issue

**Comment by dharshini2022** [comment]
@arghadipmanna101 Please label this issue under GSSOC guidelines
![Screenshot 2024-05-31 094333](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123349807/adcef34e-dfde-435e-8fc1-ac281c443225)
